steps:
  # move .env.test to.env
  - name: "bash"
    args: ["mv", ".env.test", ".env"]
    # install yarn
  - name: "gcr.io/cloud-builders/yarn"
    args: ["install"]
    # run test
  - name: "gcr.io/cloud-builders/yarn"
    args: ["run", "test"]
    # build project
  - name: "gcr.io/cloud-builders/yarn"
    args: ["run", "build"]
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/$PROJECT_ID/comment-management:$SHORT_SHA", "."]
  # k8s setting apply
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "k8s/"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-west1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=loadbalance"
  # Update container image to GKE
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment/web",
        "web=gcr.io/$PROJECT_ID/comment-management:$SHORT_SHA",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=us-west1-a"
      - "CLOUDSDK_CONTAINER_CLUSTER=loadbalance"
# Push the container image to Container Registry
images:
  [
    "gcr.io/$PROJECT_ID/comment-management:$SHORT_SHA",
    "gcr.io/$PROJECT_ID/comment-management:latest",
  ]
