apiVersion: apps/v1
kind: Deployment
metadata:
  name: comment-management-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      run: comment-management
  template:
    metadata:
      labels:
        run: comment-management
    spec:
      containers:
        - image: gcr.io/xend-326306:comment-management:latest
          imagePullPolicy: IfNotPresent
          name: comment-management-container
          ports:
            - name: liveness-port
              containerPort: 5010
              protocol: TCP
          # env
          env:
            - name: DB_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database
