apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: default
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: gcr.io/xend-326306/comment-management:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_ACCOUNT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: database
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-connection-ip
                  key: db_host
